//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Training
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseScheduleInstructor
    {
        public long CourseScheduleId { get; set; }
        public long InstructorId { get; set; }
        public bool IsPrimary { get; set; }
    
        public virtual CourseSchedule CourseSchedule { get; set; }
        public virtual Instructor Instructor { get; set; }
    }
}
