//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Training
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseEnrollment
    {
        public CourseEnrollment()
        {
            this.Enrollments = new HashSet<Enrollment>();
        }
    
        public long CourseEnrollmentId { get; set; }
        public long CourseScheduleId { get; set; }
        public string Badge { get; set; }
        public Nullable<long> NonEmployeeId { get; set; }
        public string Note { get; set; }
        public bool IsUnenrolled { get; set; }
        public string AddUserId { get; set; }
        public System.DateTime AddDateTime { get; set; }
        public string UpdUserId { get; set; }
        public Nullable<System.DateTime> UpdDateTime { get; set; }
    
        public virtual CourseSchedule CourseSchedule { get; set; }
        public virtual NonEmployee NonEmployee { get; set; }
        public virtual ICollection<Enrollment> Enrollments { get; set; }
    }
}
