//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Training
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseSchedule
    {
        public CourseSchedule()
        {
            this.CourseEnrollments = new HashSet<CourseEnrollment>();
            this.CourseScheduleInstructors = new HashSet<CourseScheduleInstructor>();
        }
    
        public long CourseScheduleId { get; set; }
        public long CourseId { get; set; }
        public string Note { get; set; }
        public System.DateTime BeginEffDate { get; set; }
        public System.DateTime EndEffDate { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<int> TotalSeat { get; set; }
        public Nullable<long> DivisionId { get; set; }
        public Nullable<long> Frequency { get; set; }
        public string Description { get; set; }
        public string AddUserId { get; set; }
        public System.DateTime AddDateTime { get; set; }
        public string UpdUserId { get; set; }
        public Nullable<System.DateTime> UpdDateTime { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual ICollection<CourseEnrollment> CourseEnrollments { get; set; }
        public virtual Division Division { get; set; }
        public virtual ICollection<CourseScheduleInstructor> CourseScheduleInstructors { get; set; }
    }
}
