//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Training
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyPerformance
    {
        public DailyPerformance()
        {
            this.DailyPerformanceProgramLevelGroups = new HashSet<DailyPerformanceProgramLevelGroup>();
            this.ProgressDays = new HashSet<ProgressDay>();
        }
    
        public int DailyPerformanceId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int SortOrder { get; set; }
        public string AddUserId { get; set; }
        public System.DateTime AddDateTime { get; set; }
        public string UpdUserId { get; set; }
        public Nullable<System.DateTime> UpdDateTime { get; set; }
    
        public virtual ICollection<DailyPerformanceProgramLevelGroup> DailyPerformanceProgramLevelGroups { get; set; }
        public virtual ICollection<ProgressDay> ProgressDays { get; set; }
    }
}
