//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Training
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyPerformanceProgramLevelGroup
    {
        public int DailyPerformanceProgramLevelGroupId { get; set; }
        public int DailyPerformanceId { get; set; }
        public int ProgramLevelGroupId { get; set; }
        public string AddUserId { get; set; }
        public System.DateTime AddDateTime { get; set; }
        public string UpdUserId { get; set; }
        public Nullable<System.DateTime> UpdDateTime { get; set; }
    
        public virtual DailyPerformance DailyPerformance { get; set; }
        public virtual ProgramLevelGroup ProgramLevelGroup { get; set; }
    }
}
