//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Training
{
    using System;
    using System.Collections.Generic;
    
    public partial class Division
    {
        public Division()
        {
            this.ProgressDays = new HashSet<ProgressDay>();
            this.CourseSchedules = new HashSet<CourseSchedule>();
        }
    
        public long DivisionId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<ProgressDay> ProgressDays { get; set; }
        public virtual ICollection<CourseSchedule> CourseSchedules { get; set; }
    }
}
