//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Training
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrollmentInstructor
    {
        public long EnrollmentInstructorId { get; set; }
        public long EnrollmentId { get; set; }
        public long InstructorId { get; set; }
        public bool IsPrimary { get; set; }
        public string AddUserId { get; set; }
        public System.DateTime AddDateTime { get; set; }
        public string UpdUserId { get; set; }
        public Nullable<System.DateTime> UpdDateTime { get; set; }
    
        public virtual Enrollment Enrollment { get; set; }
        public virtual Instructor Instructor { get; set; }
    }
}
