//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Training
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrollmentVehicle
    {
        public EnrollmentVehicle()
        {
            this.EnrollmentVehicleRoutes = new HashSet<EnrollmentVehicleRoute>();
        }
    
        public long EnrollmentVehicleId { get; set; }
        public long EnrollmentId { get; set; }
        public string VehicleId { get; set; }
        public Nullable<double> WheelTime { get; set; }
        public string RouteAlpha { get; set; }
        public bool QualifiedTraining { get; set; }
        public bool OUGLiftRampOps { get; set; }
        public bool OUGSecurement { get; set; }
        public string VehicleGroup { get; set; }
        public string AddUserId { get; set; }
        public System.DateTime AddDateTime { get; set; }
        public string UpdUserId { get; set; }
        public Nullable<System.DateTime> UpdDateTime { get; set; }
    
        public virtual Enrollment Enrollment { get; set; }
        public virtual ICollection<EnrollmentVehicleRoute> EnrollmentVehicleRoutes { get; set; }
    }
}
