//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Training
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public Enrollment()
        {
            this.EnrollmentInstructors = new HashSet<EnrollmentInstructor>();
            this.EnrollmentTopics = new HashSet<EnrollmentTopic>();
            this.EnrollmentVehicles = new HashSet<EnrollmentVehicle>();
        }
    
        public long EnrollmentId { get; set; }
        public long CourseEnrollmentId { get; set; }
        public System.DateTime SessionDate { get; set; }
        public double LectureTime { get; set; }
        public string Note { get; set; }
        public string LetterGrade { get; set; }
        public bool IsAbsent { get; set; }
        public string AddUserId { get; set; }
        public System.DateTime AddDateTime { get; set; }
        public string UpdUserId { get; set; }
        public Nullable<System.DateTime> UpdDateTime { get; set; }
    
        public virtual CourseEnrollment CourseEnrollment { get; set; }
        public virtual Grade Grade { get; set; }
        public virtual ICollection<EnrollmentInstructor> EnrollmentInstructors { get; set; }
        public virtual ICollection<EnrollmentTopic> EnrollmentTopics { get; set; }
        public virtual ICollection<EnrollmentVehicle> EnrollmentVehicles { get; set; }
    }
}
