//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Training
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrollmentVehicleTime
    {
        public Nullable<double> TotalMinute { get; set; }
        public Nullable<double> WheelMinute { get; set; }
        public Nullable<double> LectureMinute { get; set; }
        public double LectureTime { get; set; }
        public Nullable<long> Row { get; set; }
        public long EnrollmentId { get; set; }
        public long CourseEnrollmentId { get; set; }
        public System.DateTime SessionDate { get; set; }
        public bool IsAbsent { get; set; }
        public string LetterGrade { get; set; }
        public string Note { get; set; }
        public Nullable<long> EnrollmentVehicleId { get; set; }
        public string VehicleId { get; set; }
        public Nullable<double> WheelTime { get; set; }
        public string RouteAlpha { get; set; }
        public Nullable<bool> QualifiedTraining { get; set; }
        public Nullable<bool> OUGLiftRampOps { get; set; }
        public Nullable<bool> OUGSecurement { get; set; }
        public string VehicleGroup { get; set; }
        public string Vehicle { get; set; }
        public string EquipmentGroupNum { get; set; }
        public string TrainingSeriesName { get; set; }
    }
}
