//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Training
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentGroupVehicle
    {
        public string EquipmentGroupNum { get; set; }
        public string SeriesNum { get; set; }
        public string TrainingSeriesName { get; set; }
    }
}
