//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Training
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructor
    {
        public Instructor()
        {
            this.CourseScheduleInstructors = new HashSet<CourseScheduleInstructor>();
            this.EnrollmentInstructors = new HashSet<EnrollmentInstructor>();
        }
    
        public long InstructorId { get; set; }
        public string Badge { get; set; }
        public Nullable<long> NonEmployeeId { get; set; }
        public Nullable<long> CourseTypeId { get; set; }
        public string AddUserId { get; set; }
        public System.DateTime AddDateTime { get; set; }
        public string UpdUserId { get; set; }
        public Nullable<System.DateTime> UpdDateTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<CourseScheduleInstructor> CourseScheduleInstructors { get; set; }
        public virtual CourseType CourseType { get; set; }
        public virtual ICollection<EnrollmentInstructor> EnrollmentInstructors { get; set; }
        public virtual NonEmployee NonEmployee { get; set; }
    }
}
