//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Training
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstructorEnrollmentList
    {
        public int IsPreferred { get; set; }
        public Nullable<long> RowPreferred { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
        public Nullable<long> EnrollmentInstructorId { get; set; }
        public long EnrollmentId { get; set; }
        public string Trainer { get; set; }
        public Nullable<long> CourseTypeId { get; set; }
        public string Badge { get; set; }
        public Nullable<long> NonEmployeeId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> InstructorId { get; set; }
    }
}
