//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Training
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipantWorkSeed
    {
        public int ParticipantWorkSeedId { get; set; }
        public int ParticipantId { get; set; }
        public int WorkCategoryId { get; set; }
        public System.DateTime StartDate { get; set; }
        public int WorkHour { get; set; }
        public string AddUserId { get; set; }
        public System.DateTime AddDateTime { get; set; }
        public string UpdUserId { get; set; }
        public Nullable<System.DateTime> UpdDateTime { get; set; }
    
        public virtual Participant Participant { get; set; }
        public virtual WorkCategory WorkCategory { get; set; }
    }
}
