//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Training
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipantWorkDetail
    {
        public string ProgramName { get; set; }
        public string Badge { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeNameLastFirst { get; set; }
        public int ParticipantId { get; set; }
        public int ProgramId { get; set; }
        public System.DateTime ProgressStartDate { get; set; }
        public decimal WorkHour { get; set; }
        public string WorkCategoryTitleGoal { get; set; }
        public Nullable<int> WorkCategorySortOrder { get; set; }
        public string WorkCategoryShortDescription { get; set; }
        public string WorkCategoryName { get; set; }
        public int WorkCategoryId { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public string EmployeeDivision { get; set; }
        public string EmployeeWorkShift { get; set; }
        public string EmployeeScheduledDaysOff { get; set; }
        public int Level { get; set; }
        public int ParticipantStatusId { get; set; }
        public Nullable<int> ScoreTotal { get; set; }
        public Nullable<bool> SeedValue { get; set; }
    }
}
