//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Training
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgressDay
    {
        public int ProgressDayId { get; set; }
        public int ProgressId { get; set; }
        public long DivisionId { get; set; }
        public Nullable<int> DailyPerformanceId { get; set; }
        public int ProgramLevelId { get; set; }
        public System.DateTime CalendarDate { get; set; }
        public bool ApprenticeDayOff { get; set; }
        public string SupervisorBadge { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
        public string CommentBadge { get; set; }
        public string AddUserId { get; set; }
        public System.DateTime AddDateTime { get; set; }
        public string UpdUserId { get; set; }
        public Nullable<System.DateTime> UpdDateTime { get; set; }
    
        public virtual DailyPerformance DailyPerformance { get; set; }
        public virtual ProgramLevel ProgramLevel { get; set; }
        public virtual Progress Progress { get; set; }
        public virtual Division Division { get; set; }
    }
}
