//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Training
{
    using System;
    using System.Collections.Generic;
    
    public partial class Progress
    {
        public Progress()
        {
            this.ProgressDays = new HashSet<ProgressDay>();
            this.ProgressRatingCellScores = new HashSet<ProgressRatingCellScore>();
        }
    
        public int ProgressId { get; set; }
        public int ParticipantProgramLevelGroupId { get; set; }
        public System.DateTime StartDate { get; set; }
        public int ScoreTotal { get; set; }
        public Nullable<System.DateTime> EvaluationDate { get; set; }
        public string SupervisorBadge { get; set; }
        public string SuperintendentBadge { get; set; }
        public Nullable<System.DateTime> SuperintendentApprovalDate { get; set; }
        public string ScheduledDaysOff { get; set; }
        public bool Historical { get; set; }
        public string AddUserId { get; set; }
        public System.DateTime AddDateTime { get; set; }
        public string UpdUserId { get; set; }
        public Nullable<System.DateTime> UpdDateTime { get; set; }
    
        public virtual ParticipantProgramLevelGroup ParticipantProgramLevelGroup { get; set; }
        public virtual ICollection<ProgressDay> ProgressDays { get; set; }
        public virtual ICollection<ProgressRatingCellScore> ProgressRatingCellScores { get; set; }
    }
}
