//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Training
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramLevelGroup
    {
        public ProgramLevelGroup()
        {
            this.DailyPerformanceProgramLevelGroups = new HashSet<DailyPerformanceProgramLevelGroup>();
            this.ParticipantProgramLevelGroups = new HashSet<ParticipantProgramLevelGroup>();
            this.ProgramLevels = new HashSet<ProgramLevel>();
            this.RatingCells = new HashSet<RatingCell>();
        }
    
        public int ProgramLevelGroupId { get; set; }
        public int ProgramId { get; set; }
        public string Description { get; set; }
        public int StartLevel { get; set; }
        public int EndLevel { get; set; }
        public string AddUserId { get; set; }
        public System.DateTime AddDateTime { get; set; }
        public string UpdUserId { get; set; }
        public Nullable<System.DateTime> UpdDateTime { get; set; }
    
        public virtual ICollection<DailyPerformanceProgramLevelGroup> DailyPerformanceProgramLevelGroups { get; set; }
        public virtual ICollection<ParticipantProgramLevelGroup> ParticipantProgramLevelGroups { get; set; }
        public virtual Program Program { get; set; }
        public virtual ICollection<ProgramLevel> ProgramLevels { get; set; }
        public virtual ICollection<RatingCell> RatingCells { get; set; }
    }
}
