//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Training
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        public Program()
        {
            this.Participants = new HashSet<Participant>();
            this.ProgramLevelGroups = new HashSet<ProgramLevelGroup>();
            this.WorkCategories = new HashSet<WorkCategory>();
        }
    
        public int ProgramId { get; set; }
        public string Name { get; set; }
        public string ProgramType { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public string AddUserId { get; set; }
        public System.DateTime AddDateTime { get; set; }
        public string UpdUserId { get; set; }
        public Nullable<System.DateTime> UpdDateTime { get; set; }
    
        public virtual ICollection<Participant> Participants { get; set; }
        public virtual ICollection<ProgramLevelGroup> ProgramLevelGroups { get; set; }
        public virtual ICollection<WorkCategory> WorkCategories { get; set; }
    }
}
