//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Training
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingCellScore
    {
        public RatingCellScore()
        {
            this.ProgressRatingCellScores = new HashSet<ProgressRatingCellScore>();
        }
    
        public int RatingCellScoreId { get; set; }
        public int RatingCellId { get; set; }
        public int Score { get; set; }
        public string AddUserId { get; set; }
        public System.DateTime AddDateTime { get; set; }
        public string UpdUserId { get; set; }
        public Nullable<System.DateTime> UpdDateTime { get; set; }
    
        public virtual ICollection<ProgressRatingCellScore> ProgressRatingCellScores { get; set; }
        public virtual RatingCell RatingCell { get; set; }
    }
}
