//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Training
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingCell
    {
        public RatingCell()
        {
            this.RatingCellScores = new HashSet<RatingCellScore>();
        }
    
        public int RatingCellId { get; set; }
        public int ProgramLevelGroupId { get; set; }
        public int RatingCategoryId { get; set; }
        public int SortOrderCategory { get; set; }
        public int RatingAreaId { get; set; }
        public int SortOrderArea { get; set; }
        public int RatingItemId { get; set; }
        public int SortOrderCell { get; set; }
        public string AddUserId { get; set; }
        public System.DateTime AddDateTime { get; set; }
        public string UpdUserId { get; set; }
        public Nullable<System.DateTime> UpdDateTime { get; set; }
    
        public virtual ProgramLevelGroup ProgramLevelGroup { get; set; }
        public virtual RatingArea RatingArea { get; set; }
        public virtual RatingCategory RatingCategory { get; set; }
        public virtual RatingItem RatingItem { get; set; }
        public virtual ICollection<RatingCellScore> RatingCellScores { get; set; }
    }
}
