//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Training
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorksheetParticipantDetail
    {
        public int ParticipantId { get; set; }
        public string Badge { get; set; }
        public Nullable<System.DateTime> ProgramCompletedDate { get; set; }
        public System.DateTime ProgressStartDate { get; set; }
        public int ScoreTotal { get; set; }
        public Nullable<int> Score { get; set; }
        public System.DateTime CalendarDate { get; set; }
        public string DaySupervisorBadge { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
        public string CommentBadge { get; set; }
        public int ProgramLevelGroupId { get; set; }
        public Nullable<int> RatingCategoryId { get; set; }
        public Nullable<int> RatingAreaId { get; set; }
        public Nullable<int> RatingItemId { get; set; }
        public Nullable<int> RatingCellId { get; set; }
        public Nullable<int> RatingCellScoreId { get; set; }
        public int ProgressId { get; set; }
        public int ProgressDayId { get; set; }
        public Nullable<System.DateTime> EvaluationDate { get; set; }
        public string SupervisorBadge { get; set; }
        public string SuperintendentBadge { get; set; }
        public Nullable<System.DateTime> SuperintendentApprovalDate { get; set; }
        public long DivisionId { get; set; }
        public Nullable<int> DailyPerformanceId { get; set; }
        public int ParticipantStatusId { get; set; }
        public int ProgramLevelId { get; set; }
        public int ParticipantProgramLevelGroupId { get; set; }
        public int ProgramId { get; set; }
    }
}
