//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Training
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorksheetTemplate
    {
        public string ProgramGroup { get; set; }
        public string Category { get; set; }
        public string Area { get; set; }
        public string Item { get; set; }
        public int SortOrderCategory { get; set; }
        public int SortOrderArea { get; set; }
        public int SortOrderCell { get; set; }
        public int RatingCellId { get; set; }
        public int ProgramLevelGroupId { get; set; }
        public int RatingCategoryId { get; set; }
        public int RatingAreaId { get; set; }
        public int RatingItemId { get; set; }
        public int StartLevel { get; set; }
        public Nullable<long> SortOrder { get; set; }
    }
}
