//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACTransit.Entities.Training
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkCategory
    {
        public WorkCategory()
        {
            this.ParticipantWorks = new HashSet<ParticipantWork>();
            this.ParticipantWorkSeeds = new HashSet<ParticipantWorkSeed>();
        }
    
        public int WorkCategoryId { get; set; }
        public int ProgramId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ShortDescription { get; set; }
        public int HourGoal { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<System.DateTime> InactiveDate { get; set; }
        public string AddUserId { get; set; }
        public System.DateTime AddDateTime { get; set; }
        public string UpdUserId { get; set; }
        public Nullable<System.DateTime> UpdDateTime { get; set; }
    
        public virtual ICollection<ParticipantWork> ParticipantWorks { get; set; }
        public virtual ICollection<ParticipantWorkSeed> ParticipantWorkSeeds { get; set; }
        public virtual Program Program { get; set; }
    }
}
